name: AppSync Client build and publish 
on: 
  push:
    branches:
      - github-actions
jobs:
  Publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install depenedencies
        run: npm install
        working-directory: ./packages/appsync-client
      - name: Build
        run: npm run build
        working-directory: ./packages/appsync-client
      - name: publish version
        id: publish
        run: npm publish
        working-directory: ./packages/appsync-client
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: version number
        if: steps.publish.output.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
