name: AppSync Client build and publish 
on: 
  push:
    branches:
      - github-actions
jobs:
  Publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Build
        run: npm run build
      - name: npm Publish
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with: 
          token: ${{ secrets.NPM_TOKEN }}
      - name: Get Version number
      - if: steps.publish.output.type != 'none'
        run: |
          echo "Version changed: ${{ steps.published.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
