name: Deploy CLI
on: 
  push:
    branches:
      - github-actions
    paths:
      - 'packages/api/**'
jobs:
  Publish-package:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: npm build
        working-directory: ./packages/api
        run: npm run build
      - name: checkout repo
        uses: actions/checkout@v2
      - name: publish version
        id: publish
        uses: pascalgn/npm-publish-action@1.3.8
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: version number
        if: steps.publish.output.type != 'none'
        run: |
          echo "Version changed: ${{ steps.published.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
# Look into GitHub release, if easy, do it, if not, put into backlog
#  Npm run build... then publish