name: Deploy CLI
on: 
  push:
    branches:
      - github-actions
    paths:
      - 'packages/api/**'
jobs:
  Publish-package:
    runs-on: ubuntu-latest
    steps:
      - id: publish
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./packages/api
      - name: npm build
        run: npm run build
      - name: npm publish
        uses: JS-DevTools/npm-publish@v1
        with: 
          token: ${{ secrets.NPM_TOKEN }} 
      - name: Find version numbers
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
