name: Deploy CLI
on: 
  push:
    branches:
      - github-actions
    paths:
      - 'packages/api/**'
jobs:
  Publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - id: publish
      - working-directory: ./packages/api
      - run: |
          npm install
          npm run build
      - name: npm publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          
#       - if: steps.publish.outputs.type != 'none'
#         run: |
#           echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
# Look into GitHub release, if easy, do it, if not, put into backlog
