name: Deploy CLI
on: 
  push:
    branches:
      - github-actions
    paths:
      - 'packages/api/**'
jobs:
  Publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install depenedencies
        run: npm install
        working-directory: ./packages/cli
      - name: Build
        run: npm run build
        working-directory: ./packages/cli
      - name: publish version
        id: publish
        run: npm publish
        working-directory: ./packages/cli
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: version number
        if: steps.publish.output.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
# Look into GitHub release, if easy, do it, if not, put into backlog
#  Npm run build... then publish
