name: Deploy CLI
on: 
  push:
    branches:
      - github-actions
    paths:
      - 'packages/api/**'
jobs:
  Publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        run: npm build
      - name: NPM publish
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with: 
          token: ${{ secrets.NPM_TOKEN }}
      - name: Get Version number
      - if: steps.publish.output.type != 'none'
        run: |
          echo "Version changed: ${{ steps.published.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
# Look into GitHub release, if easy, do it, if not, put into backlog