name: Deploy Api
on: 
  push:
    branches:
      - master
    paths:
      - 'packages/api/**'
      - '.github/workflows/deploy-api.yml'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: install dependencies
        run: npm install
        working-directory: ./packages/api
      - name: Unit Tests
        working-directory: ./packages/api
        run: npm test
      - name: Configure AWS for Prod
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_NONPROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_NONPROD_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to Taylor
        working-directory: ./packages/api
        run: npx sls deploy -v --stage taylor