name: Publish NPM on push to main
on: 
  push:
    branches:
      - github-actions
jobs:
  Publish-package:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: publish version
        id: publish
        uses: pascalgn/npm-publish-action@1.3.8
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: version number
        if: steps.publish.output.type != 'none'
        run: |
          echo "Version changed: ${{ steps.published.outputs.old-version }} => ${{ steps.publish.outputs.version }}"